### ISSUE TITLE
All videos within a folder get the same metadata

### ISSUE THREAD

**Issue by GiovanH** [ankenyr/jellyfin-youtube-metadata-plugin#47] opened 2022-04-30 19:41 UTC
I have youtube videos arranged by channel, with the IDs in square brackets and accompanying info.json files:

![image](https://user-images.githubusercontent.com/6759280/166120231-80dc5d86-6157-4546-8c01-b3ad41c3131a.png)

But when jellyfin runs, the youtube provider gives every video in the folder the same metadata, even though the info.json files are correct:

![image](https://user-images.githubusercontent.com/6759280/166120283-5be33e8c-e4a5-44fc-ada8-e79ed6b47aa6.png)

I haven't been able to find much in the way of logs to debug this, so any pointers would be greatly appreciated.

**Comment by ankenyr** [comment] 2022-04-30 21:20
Which version of the plugin are you on? This was a big in an earlier
version.
I will be taking some time to add debug logs in soon to help with others
who have had issues lately. Been getting ramped up at a new place so I have
not had much time to work on the plugin. Expect to get some time this week
though.

**Comment by GiovanH** [comment] 2022-04-30 21:22
This is on version 1.0.3.5 on Jellyfin 10.8

**Comment by ankenyr** [comment] 2022-04-30 21:24
Weird, I will have to check my own server when I get home because I also
have petscop.

**Comment by GiovanH** [comment] 2022-05-01 21:07
To be clear, this isn't limited to petscop, that was just the example I was using. This is a global problem.

**Comment by HStep20** [comment] 2022-05-02 17:26
I'd like to echo the same problem. Every one of my videos is named as instructed, but they all have the same metadata - minus the thumbnail. 

Jellyfin Version: 10.8.0

Plugin Version: 1.0.3.5

**Comment by GiovanH** [comment] 2022-05-03 05:45
Also, the log output on the console reads
```
[05:44:08] [INF] [26] Jellyfin.Plugin.YoutubeMetadata.Providers.YTDLEpisodeProvider: Youtube ID not found in filename of title: {info.Name}
[05:44:08] [INF] [26] Jellyfin.Plugin.YoutubeMetadata.Providers.YoutubeDL.YTDLImageProvider: Youtube ID not found in filename of title: {item.Name}
[05:44:11] [INF] [23] Jellyfin.Plugin.YoutubeMetadata.Providers.YTDLEpisodeProvider: Youtube ID not found in filename of title: {info.Name}
[05:44:11] [INF] [23] Jellyfin.Plugin.YoutubeMetadata.Providers.YoutubeDL.YTDLImageProvider: Youtube ID not found in filename of title: {item.Name}
[05:44:12] [INF] [30] Jellyfin.Plugin.YoutubeMetadata.Providers.YTDLEpisodeProvider: Youtube ID not found in filename of title: {info.Name}
[05:44:12] [INF] [30] Jellyfin.Plugin.YoutubeMetadata.Providers.YoutubeDL.YTDLImageProvider: Youtube ID not found in filename of title: {item.Name}
[05:44:13] [INF] [30] Jellyfin.Plugin.YoutubeMetadata.Providers.YTDLEpisodeProvider: Youtube ID not found in filename of title: {info.Name}
[05:44:13] [INF] [30] Jellyfin.Plugin.YoutubeMetadata.Providers.YoutubeDL.YTDLImageProvider: Youtube ID not found in filename of title: {item.Name}
[05:44:14] [INF] [30] Jellyfin.Plugin.YoutubeMetadata.Providers.YTDLEpisodeProvider: Youtube ID not found in filename of title: {info.Name}
[05:44:14] [INF] [30] Jellyfin.Plugin.YoutubeMetadata.Providers.YoutubeDL.YTDLImageProvider: Youtube ID not found in filename of title: {item.Name}
[05:44:15] [INF] [25] Jellyfin.Plugin.YoutubeMetadata.Providers.YTDLEpisodeProvider: Youtube ID not found in filename of title: {info.Name}
[05:44:15] [INF] [25] Jellyfin.Plugin.YoutubeMetadata.Providers.YoutubeDL.YTDLImageProvider: Youtube ID not found in filename of title: {item.Name}
[05:44:17] [INF] [30] Jellyfin.Plugin.YoutubeMetadata.Providers.YTDLEpisodeProvider: Youtube ID not found in filename of title: {info.Name}
[05:44:17] [INF] [30] Jellyfin.Plugin.YoutubeMetadata.Providers.YoutubeDL.YTDLImageProvider: Youtube ID not found in filename of title: {item.Name}
```

I think this is just bad code here https://github.com/ankenyr/jellyfin-youtube-metadata-plugin/blob/8dfdb60d8b3bce15f14fd2d83c8ea33919398ab9/Jellyfin.Plugin.YoutubeMetadata/Providers/YoutubeDL/YTDLImageProvider.cs#L66

**Comment by Galalalallalalaxyyyy** [comment] 2022-05-05 05:19
I have the same problem each one of the videos in the same folder all have the same metadata.

**Comment by ankenyr** [comment] 2022-05-08 21:57
Just uploaded a new version, I believe there are still some bugs that need to be worked out but the duplicate episodes thing should be resolved.

**Comment by HStep20** [comment] 2022-05-08 22:28
If it's not 1.0.3.6, the build from 3 days ago, I'll check it out once I see it install and confirm. 
I tested with 1.0.3.6 when I saw it pop up Friday, but didn't have any luck fixing things with a full refresh

**Comment by GiovanH** [comment] 2022-05-09 02:44
That seems to have broken the plugin entirely. 
```
[02:42:54] [ERR] [1] Emby.Server.Implementations.Plugins.PluginManager: Failed to load assembly /config/plugins/YoutubeMetadata_1.0.3.6/Jellyfin.Plugin.YoutubeMetadata.dll. This error occurs when a plugin references an incompatible version of one of the shared libraries. Disabling plugin.
System.Reflection.ReflectionTypeLoadException: Unable to load one or more of the requested types.
Method 'ExecuteAsync' in type 'Jellyfin.Plugin.YoutubeMetadata.EpisodeIndexer' from assembly 'Jellyfin.Plugin.YoutubeMetadata, Version=1.0.3.6, Culture=neutral, PublicKeyToken=null' does not have an implementation.
   at System.Reflection.RuntimeModule.GetTypes(RuntimeModule module)
   at System.Reflection.Assembly.GetTypes()
   at Emby.Server.Implementations.Plugins.PluginManager.LoadAssemblies()+MoveNext()
System.TypeLoadException: Method 'ExecuteAsync' in type 'Jellyfin.Plugin.YoutubeMetadata.EpisodeIndexer' from assembly 'Jellyfin.Plugin.YoutubeMetadata, Version=1.0.3.6, Culture=neutral, PublicKeyToken=null' does not have an implementation.
```

**Comment by ankenyr** [comment] 2022-05-09 02:51
Sorry, can you be more explicit? What cause it to fail entirely?

**Comment by GiovanH** [comment] 2022-05-09 02:53
I attached the exact log above. It fails to load on program start.

**Comment by ankenyr** [comment] 2022-05-09 04:04
Ok but I still need to understand what version you are running down to specific builds. I was targeting the latest alpha (5) for building against. Searching the issues on Jellyfin it seems like maybe you are running unstable? https://github.com/jellyfin/jellyfin/issues/7351
If you are running unstable then you should expect that things will break.

**Comment by GiovanH** [comment] 2022-05-09 04:29
So what specific version/tag of jellyfin does this target? I don't see anything in the readme requirements

**Comment by GiovanH** [comment] 2022-05-18 23:37
?

**Comment by ilkersigirci** [comment] 2022-06-11 19:59
I also have this issue with jellyfin 10.8.0 and plugin version 1.0.3.7

**Comment by GiovanH** [comment] 2022-06-13 05:01
`Jellyfin.Plugin.YoutubeMetadata.Providers.YTDLEpisodeProvider: YTDL GetMetadata: Youtube ID not found in filename of title: {info.Name}` issue persists.

**Comment by nothing2obvi** [comment] 2022-06-15 02:51
> I also have this issue with jellyfin 10.8.0 and plugin version 1.0.3.7

Same

**Comment by iamdangry** [comment] 2022-06-15 09:14
Also experiencing the issue with Jellyfin 10.8.0 and plugin 1.0.3.7

Have noticed the YT MetaData field is empty within Jellyfin. Manually adding the YT video ID and refreshing the metadata resolves the issue. Obviously not a solution, but possibly the source of the problem that the plugin isn't either adding or extracting the YT ID correctly.

**Comment by ankenyr** [comment] 2022-06-15 16:13
This is super weird because I haven't been able to replicate this since
early in the development. If you understand that this is replicable can
someone who possibly has a dockerized version or can just launch a second
instance of jelly fin do that? Basically what I'm looking for is given the
file structures being exactly the same, given a new instance and a fresh
database with nothing else being created will it do the same. If someone
can do that and confirm that replicates that would be very helpful.

**Comment by HStep20** [comment] 2022-06-15 18:08
Did a completely fresh install for you, and still seeing the same problem. yt-dlp is installed in the container, and it is grabbing stuff like channel logos correctly, but episode names are still borked.

File path looks like: "Brandon_Sanderson\2020_Creative_Writing_Lectures[PLSH_xM-KC3Zv-79sVZTTj-YA6IAqh8qeQ]\Brandon Sanderson - 20200122 - Lecture #1 Introduction — Brandon Sanderson on Writing Science Fiction and Fantasy [-6HOdHEeosc].mkv/.info.json/.nfo/.jpg"

Similar structure for all of my sources. Weird thing is that some of them view each file as a different version of one episode, where others show each individual episode with the right thumbnail, but wrong title/info.

**Comment by ankenyr** [comment] 2022-06-16 04:48
This might require a different issue but @HStep20, why is your directory structure like that? For myself I use https://github.com/TheFrenchGhosty/TheFrenchGhostys-Ultimate-YouTube-DL-Scripts-Collection as my basis and it ends up with an output like `ChannelName/Year/Username - Upload Date - Title/Username - Upload Date - Title [ID].ext`

Are you expecting playlists to be generated for you via my plugin, or another?

Do others here have vastly different directory trees than what I have described above?

**Comment by ankenyr** [comment] 2022-06-16 04:49
Also for each person, what tools besides yt-dlp are you using? TubeArchivist? Something else?

**Comment by GiovanH** [comment] 2022-06-16 04:51
With jellyfin in a container, how do you recommend injecting yt-dlp?

**Comment by GiovanH** [comment] 2022-06-16 05:11
Seems to be working better now, I'll keep poking at it

**Comment by iamdangry** [comment] 2022-06-16 05:24
yt-dlp only

Filetree was `ChannelName/Title_[ID].ext` or `ChannelName/Season [int]/Title_[ID].ext`

Placing each video into its own folder like `ChannelName/Title/Title_[ID].ext` or `ChannelName/Season [int]/Title/Title_[ID].ext` resolves the issue

**Comment by GiovanH** [comment] 2022-06-16 05:36
A lot of the metadata is right now, but the season and episode numbers are locked at 1, so petscop is still all screwed up since it's sorting by title lexographically.

**Comment by iamdangry** [comment] 2022-06-16 06:00
Sorted two channels worth of videos using the new directory structure above
Ran a metadata refresh to ensure it was functioning correctly and noticed the other channels are now recieving the correct metadata without being sorted into a new directory structure. So not all videos are dependant on the correct folder structure

**Comment by ankenyr** [comment] 2022-06-16 06:23
but unsorted ones magically started working? Did all videos get resolved or just some?

**Comment by iamdangry** [comment] 2022-06-16 06:46
> but unsorted ones magically started working? Did all videos get resolved or just some?

Correct. **All** videos within my YT library, whether sorted or unsorted, now have the correct metadata (except for the episode number issue mentioned by GiovanH). Will try to recreate the issue using the videos I've sorted and post any log entries

**Comment by iamdangry** [comment] 2022-06-16 08:25
So I've been fiddling for a few hours with a new library.

Directory structure is important and the issue appears if I have more than 2 videos **NOT** contained in their own subfolders.

### What produced the issue:
More than 2 videos **NOT** in their own subfolders **and** running "Refresh Metadata". Running "Replace Metadata" resolved the incorrect metadata until the next "Refresh Metadata" was ran.
The below folder structure did **not** create the metadata issue when using "Refresh Metadata":
```
ChannelA/Title1 [ID].ext
ChannelA/Title2 [ID].ext
```
OR
```
ChannelA/Title1 [ID].ext
ChannelB/Title1 [ID].ext
```

But when I added a third video, the metadata issue returned when using "Refresh Metadata":
```
ChannelA/Title1 [ID].ext
ChannelA/Title2 [ID].ext
ChannelA/Title3 [ID].ext
```
OR
```
ChannelA/Title1 [ID].ext
ChannelA/Title2 [ID].ext
ChannelB/Title1 [ID].ext
```


### What resolved the issue:
All videos being in their own subfolder - didn't matter if I ran "refresh metadata" or "replace metadata", videos recieved correct metadata

My folder structure now:
`ChannelName/Title/Title [ID].ext` or if I'm grouping by seasons `ChannelName/Season [int]/Title/Title [ID].ext`

What I hadn't picked up on earlier is the issue going away when running "Replace" instead of "Refresh" when there was more than 2 videos not in their own subfolder. Hence the odd magical fix.

**Comment by GiovanH** [comment] 2022-06-16 22:39
I just came back to my library (which had retrieved correct metadata) and found that it rescanned overnight and *replaced* that good metadata with bad metadata (all the same). My folder structure is `{channel}/{date} {title} [{id}]`

**Comment by HStep20** [comment] 2022-06-17 04:27
> This might require a different issue but @HStep20, why is your directory structure like that? For myself I use https://github.com/TheFrenchGhosty/TheFrenchGhostys-Ultimate-YouTube-DL-Scripts-Collection as my basis and it ends up with an output like `ChannelName/Year/Username - Upload Date - Title/Username - Upload Date - Title [ID].ext`
> 
> Are you expecting playlists to be generated for you via my plugin, or another?

Nope, not expecting playlists. Just using it to help with identification. Im using TubeSync, which lets you define patterns for naming of downloads since the TubeArchivist naming system doesnt work with this plugin. 

For all of my series, the naming scheme is set up to look like: *"{Channel_Name}/{Playlist_Title}[Playlist_Key]/{Channel_Name} - {yyyymmdd} - {title_full} [{key}].{ext}"*

**Comment by GiovanH** [comment] 2022-06-20 05:13
@ankenyr Please take a look at @iamdangry 's comment; it looks like this is a bug related to folder structure, so knowing that may make it easier to fix

**Comment by ankenyr** [comment] 2022-06-20 06:22
So far I have not been able to replicate this on Windows where I do my general development. I may have replicated this on Linux in docker but the server is frozen and I need to hit the hay. Will check it tomorrow. For anyone having this issue, is anyone on Windows by any chance?

**Comment by BlueRocketMouse** [comment] 2022-06-20 14:41
I'm on Windows and can confirm that the issue exists there too. iamdangry's fix of putting every video in its own subfolder worked for me, aside from the aforementioned issue of episodes sorting alphabetically by title instead of chronologically by date. My folder prior to giving every video its own folder was: Channel [ID]/Videos/Upload Date - Title [ID].ext

Windows 10 Pro, Jellyfin 10.8.0, plugin version 1.0.3.7

**Comment by iamdangry** [comment] 2022-06-21 02:46
My main Jellyfin server is Ubuntu 20.04.4

I've just spun up a Windows 10 Pro box (20H2) and can confirm this issue exists on Windows and goes away using the folder structure I wrote above. Working on updating it to the latest version of Win10 to see if the problem still exists

**Comment by ankenyr** [comment] 2022-06-21 06:27
Ok I think I replicated it but I am seeing something slightly different. I think this may have to do with the sorting as mentioned by @BlueRocketMouse.
![image](https://user-images.githubusercontent.com/1542958/174730439-d95ac34e-06a5-426e-b155-65d000b8987a.png)

![image](https://user-images.githubusercontent.com/1542958/174730561-b8e43ece-59fa-4cc3-9a52-b94bbf43bae1.png)

I am unsure how to sort by other means as mentioned. I will take a look and see what is causing this but I suspect that the answer here may be that a "season folder" of some sort is required.

**Comment by GiovanH** [comment] 2022-06-23 04:01
My output looks even worse than yours. 
Here is my petscop directory tree:

```
> tree petscop
petscop
├── 20170312 [6e6RK8o1fcs] Petscop.en.vtt
├── 20170312 [6e6RK8o1fcs] Petscop.info.json
├── 20170312 [6e6RK8o1fcs] Petscop.mkv
├── 20170312 [6e6RK8o1fcs] Petscop.nfo
├── 20170401 [teJDdkWHAdw] Petscop 2.en.vtt
├── 20170401 [teJDdkWHAdw] Petscop 2.info.json
├── 20170401 [teJDdkWHAdw] Petscop 2.mkv
├── 20170401 [teJDdkWHAdw] Petscop 2.nfo
├── 20170402 [FqyhmoMdeC8] Petscop 3.en.vtt
├── 20170402 [FqyhmoMdeC8] Petscop 3.info.json
├── 20170402 [FqyhmoMdeC8] Petscop 3.mkv
├── 20170402 [FqyhmoMdeC8] Petscop 3.nfo
├── 20170531 [RAM0bcJnijg] Petscop 10.en.vtt
├── 20170531 [RAM0bcJnijg] Petscop 10.info.json
├── 20170531 [RAM0bcJnijg] Petscop 10.mkv
├── 20170531 [RAM0bcJnijg] Petscop 10.nfo
├── 20171225 [nXHUw2nw6aA] Petscop 11.en.vtt
├── 20171225 [nXHUw2nw6aA] Petscop 11.info.json
├── 20171225 [nXHUw2nw6aA] Petscop 11.mkv
├── 20171225 [nXHUw2nw6aA] Petscop 11.nfo
├── 20180104 [y82EsETuMbM] Petscop 12.en.vtt
├── 20180104 [y82EsETuMbM] Petscop 12.info.json
├── 20180104 [y82EsETuMbM] Petscop 12.mkv
├── 20180104 [y82EsETuMbM] Petscop 12.nfo
├── 20191128 [JB82_-Ngucc] Petscop Soundtrack.en.vtt
├── 20191128 [JB82_-Ngucc] Petscop Soundtrack.info.json
├── 20191128 [JB82_-Ngucc] Petscop Soundtrack.mkv
├── 20191128 [JB82_-Ngucc] Petscop Soundtrack.nfo
├── archive.txt
├── backdrop.jpg
├── folder.jpg
├── metadata
│   ├── 20170312 [6e6RK8o1fcs] Petscop.webp
│   ├── 20170401 [teJDdkWHAdw] Petscop 2.webp
│   ├── 20170402 [FqyhmoMdeC8] Petscop 3.webp
│   ├── 20170407 [IwaRKux9eR8] Petscop 4.webp
│   ├── 20170411 [hta3dc5qDNw] Petscop 5.webp
│   ├── 20170420 [c_zCl8GV_dE] Petscop 6.webp
│   ├── 20170429 [sTDv4sgwios] Petscop 7.webp
│   ├── 20170509 [XPDbQMGFUL8] Petscop 8.webp
│   ├── 20170524 [nogEDJu2Z4c] Petscop 9.webp
│   ├── 20170531 [RAM0bcJnijg] Petscop 10.webp
│   ├── 20171225 [nXHUw2nw6aA] Petscop 11.webp
│   ├── 20180104 [y82EsETuMbM] Petscop 12.webp
│   ├── 20180311 [2ZqR5StCDt0] Petscop 13.webp
│   ├── 20180717 [OPzYMFdyKQQ] Petscop 14.jpg
│   ├── 20180718 [PiH04RGXYKo] Petscop 15.webp
│   ├── 20181031 [BmTyTN-J6ZU] Petscop 16.webp
│   ├── 20190420 [Ew4HcmqPWhw] Petscop 17.webp
│   ├── 20190421 [5pq0NeOMEGw] Petscop 21.webp
│   ├── 20190421 [bwjvp_HJ62c] Petscop 19.webp
│   ├── 20190421 [gRpCY8fr070] Petscop 20.jpg
│   ├── 20190421 [Zp-AIcnBSXg] Petscop 18.webp
│   ├── 20190901 [2KsWlk79rng] Petscop 24.webp
│   ├── 20190901 [iJtIcSyqYa4] Petscop 22.webp
│   ├── 20190901 [P-nUhmeo87I] Petscop 23.webp
│   └── 20191128 [JB82_-Ngucc] Petscop Soundtrack.webp
├── Thumbs.db
└── tvshow.nfo
```
And here is the display:
![image](https://user-images.githubusercontent.com/6759280/175206311-e561c10b-8510-4d16-9440-46ba28f27225.png)
![image](https://user-images.githubusercontent.com/6759280/175206327-871affc9-37d9-4a06-b4d2-6ca582c4d732.png)

**Comment by ankenyr** [comment] 2022-06-23 06:39
Ok I may have found it, for others who are experiencing this, can you confirm if the info.json files have empty strings for the video description?
![image](https://user-images.githubusercontent.com/1542958/175231665-c1f9e4c5-3d2d-4248-98ba-cb2bd4538b45.png)

Modifying this with a simple string gets that episode to update to that string, removing it returns it to the first episode description.

**Comment by iamdangry** [comment] 2022-06-23 06:46
Nope, mine all have a value in description

**Comment by ankenyr** [comment] 2022-06-23 06:47
can you give me the tree structure and images similar to GiovanH above?

**Comment by iamdangry** [comment] 2022-06-23 07:02
I'm using a new structure as I've documented further up in this thread so it works for now. I've listed both my work structure and non-working structure

# What works:
Note: The season folder only exists to prevent a new season being created for each video. It has no impact on the issue
```
All Gas No Brakes
└──Season 1
    ├── AlienCon
    │   ├── AlienCon_[bI6SPBFCqcQ].info.json
    │   ├── AlienCon_[bI6SPBFCqcQ].jpg
    │   └── AlienCon_[bI6SPBFCqcQ].mp4
    ├── A Night In Las Vegas
    │   ├── A Night in Las Vegas_[ToaSW0bjMT4].info.json
    │   ├── A Night in Las Vegas_[ToaSW0bjMT4].jpg
    │   └── A Night in Las Vegas_[ToaSW0bjMT4].mp4
    ├── AVN Expo
    │   ├── AVN Expo_[QjidbxN6geg].info.json
    │   ├── AVN Expo_[QjidbxN6geg].jpg
    │   └── AVN Expo_[QjidbxN6geg].mp4
    ├── Bigfoot Hunting
    │   ├── Bigfoot Hunting_[wsXhk1xmYAI].info.json
    │   ├── Bigfoot Hunting_[wsXhk1xmYAI].jpg
    │   └── Bigfoot Hunting_[wsXhk1xmYAI].mp4
```
![image](https://user-images.githubusercontent.com/46516977/175234245-aed87082-4dab-41ce-a144-be484239bfbe.png)

# What doesn't work:
```
All Gas No Brakes
    └── Season 1
        ├── AlienCon_[bI6SPBFCqcQ].info.json
        ├── AlienCon_[bI6SPBFCqcQ].jpg
        ├── AlienCon_[bI6SPBFCqcQ].mp4
        ├── A Night in Las Vegas_[ToaSW0bjMT4].info.json
        ├── A Night in Las Vegas_[ToaSW0bjMT4].jpg
        ├── A Night in Las Vegas_[ToaSW0bjMT4].mp4
        ├── AVN Expo_[QjidbxN6geg].info.json
        ├── AVN Expo_[QjidbxN6geg].jpg
        ├── AVN Expo_[QjidbxN6geg].mp4
        ├── Bigfoot Hunting_[wsXhk1xmYAI].info.json
        ├── Bigfoot Hunting_[wsXhk1xmYAI].jpg
        └── Bigfoot Hunting_[wsXhk1xmYAI].mp4
```
![image](https://user-images.githubusercontent.com/46516977/175234927-77e27c36-7b7a-4502-8eb5-9b77784e42c1.png)

**Comment by ankenyr** [comment] 2022-06-24 04:52
@iamdangry When I first put the files in place and scan I see what you are seeing but after the first run of the plugin they are fixed.

**Comment by ankenyr** [comment] 2022-06-24 05:04
Surprise I see this issue was filed a a couple weeks ago, it popped up in discussion in the dev channel.
https://github.com/jellyfin/jellyfin/issues/7855

In all honesty this is all looking to be issues internal to jellyfin itself. When looking at the petscop media my plugin does return a empty string. I was suspecting it may have not actually added anything for Overview which could have caused a problem.
![image](https://user-images.githubusercontent.com/1542958/175465677-192a70de-edd5-40f5-9a3d-56e00c7cbb7e.png)

This all feels to me like internal issues to Jellyfin itself sadly which is not something I can fix. I am sorry. I will try to investigate a bit more and make an issue on the jellyfin repo.

**Comment by GiovanH** [comment] 2022-06-24 05:28
I have never seen the "version" case you're describing. That seems unrelated to the issue I reported here.

**Comment by ankenyr** [comment] 2022-06-24 05:40
Kept debugging, seems it is on me. I stepped through the yt-dl plugin until it exited into the metadata service file. I followed it down and noticed a line.
`var localItem = await provider.GetMetadata(itemInfo, options.DirectoryService, cancellationToken).ConfigureAwait(false);`
where I finally saw it grab the wrong information.
Stepping into that surprisingly it went into my local provider. There I see this line.
https://github.com/ankenyr/jellyfin-youtube-metadata-plugin/blob/master/Jellyfin.Plugin.YoutubeMetadata/Providers/LocalMetadata/AbstractYoutubeLocalProvider.cs#L83

Specifically the issue is `info.ContainingFolderPath`

Running a refresh and the youtube metadata task to renumber the episodes it now looks right to me.

![image](https://user-images.githubusercontent.com/1542958/175469656-5e9886b0-6f52-46ff-b0ad-a2f545d3d9e6.png)

@GiovanH if I sent you the files as they are now. Could you

**Comment by ankenyr** [comment] 2022-06-24 06:08
https://github.com/ankenyr/jellyfin-youtube-metadata-plugin/commit/93f4b2784bca74133f7b9ad08c358ba4f608cff0 should fix this.
I have some spare time tomorrow and would like to tackle https://github.com/ankenyr/jellyfin-youtube-metadata-plugin/issues/40 before pushing out a new version.

**Comment by ankenyr** [comment] 2022-07-02 04:29
This has been released in the latest as #40 will take a bit more work than I thought.

**Closed by ankenyr** 2022-07-02 04:29 UTC

**Comment by NonImportantPerson** [comment] 2022-10-11 07:07
Thanks I will try it out

-------- Original Message --------

**Comment by ankenyr** [comment] 2022-10-11 08:08
For those who have not shared yet, what do some of your filename formats
look like? The same as OPs?

**Comment by ankenyr** [comment] 2022-10-11 08:47
I believe I said alpha 5 in the previous message. Are you running unstable
or some other build?
