### ISSUE TITLE
Plugin does not use .info.json file provided by my yt-dlp based script

### ISSUE THREAD

**Issue by pixselious** [ankenyr/jellyfin-youtube-metadata-plugin#71] opened 2022-09-26 12:48 UTC
### My setup:
**Jellyfin 10.8.5** on **macOS** (native install, not docker)
**Plugin 1.0.3.9** (shows up as 1.0.3.8)
**yt-dlp 2022.09.01** (my script just automates downloads using yt-dlp)

The plugin is set as the primary metadata reader, but I use my own script as a metadata downloader. 

### Issue:
The plugin does not add any metadata to the videos. When I scanned the library, replacing all metadata, metadata from videos that were downloaded before I updated the server disappeared. 

This started happening since I updated Jellyfin from 10.7.7 to 10.8.5. I did not change my script, so I don't think that it causes the issue.

I have tried to use the plugin as a metadata downloader: I installed yt-dlp on my system using brew, reinstalled the plugin, restarted the server, but it says that it can not find the youtube-dl install.

**Comment by ankenyr** [comment] 2022-09-26 14:31
Do you have logs?

**Comment by pixselious** [comment] 2022-09-26 15:17
The debug logs print loads of stuff, I think this is the part that you want to see. 
I ran a library scan, told it to replace all metadata and images. 

Here is how my files are organized:
Jellyfin media -> Audiobooks -> 1984 [id] -> 1984 [id].info.json /  1984 [id].mp4 / poster.jpg 
(My other library does not have cyrillic characters in the filnames, but has the same issue.)

`[2022-09-26 18:06:59.165 +03:00] [DBG] [66] MediaBrowser.Providers.Folders.CollectionFolderMetadataService: Running "CollectionFolderImageProvider" for "/Users/mathew/.local/share/jellyfin/root/default/Аудиокниги"
[2022-09-26 18:06:59.166 +03:00] [INF] [66] Emby.Drawing.ImageProcessor: Creating image collage and saving to "/Users/mathew/.cache/jellyfin/temp/2076ae28983147778c58e3d782e77bbc.png"
[2022-09-26 18:06:59.552 +03:00] [INF] [66] Emby.Drawing.ImageProcessor: Completed creation of image collage and saved to "/Users/mathew/.cache/jellyfin/temp/2076ae28983147778c58e3d782e77bbc.png"
[2022-09-26 18:06:59.553 +03:00] [DBG] [66] MediaBrowser.Providers.Manager.ProviderManager: Saving image to "/Users/mathew/.local/share/jellyfin/metadata/library/ff/ff5cfbe68eb4f8d84727ffcce4f1f290/poster.png"
[2022-09-26 18:06:59.556 +03:00] [DBG] [68] Emby.Drawing.ImageProcessor: Getting image size for item "CollectionFolder" "/Users/mathew/.local/share/jellyfin/metadata/library/ff/ff5cfbe68eb4f8d84727ffcce4f1f290/poster.png"
[2022-09-26 18:06:59.623 +03:00] [DBG] [68] MediaBrowser.Providers.Folders.FolderMetadataService: Running "FolderImageProvider" for "/Volumes/HDD/Jellyfin media/1 Аудиокниги"
[2022-09-26 18:06:59.628 +03:00] [DBG] [68] MediaBrowser.Providers.Manager.ProviderManager: OnRefreshStart "cffeae530ea96d3917384f0d9e88033f"
[2022-09-26 18:06:59.628 +03:00] [DBG] [68] MediaBrowser.Providers.Manager.ProviderManager: OnRefreshProgress "cffeae530ea96d3917384f0d9e88033f" 5
[2022-09-26 18:06:59.770 +03:00] [DBG] [68] MediaBrowser.Providers.Manager.ProviderManager: OnRefreshProgress "cffeae530ea96d3917384f0d9e88033f" 10
[2022-09-26 18:06:59.770 +03:00] [DBG] [100] MediaBrowser.Providers.Manager.ProviderManager: OnRefreshStart "5b8c78c20b62e3dd497dae35fedfc581"
[2022-09-26 18:06:59.770 +03:00] [DBG] [68] MediaBrowser.Providers.Manager.ProviderManager: OnRefreshStart "3b7cc628881540e02c869d16aed0acd0"
[2022-09-26 18:06:59.770 +03:00] [DBG] [100] MediaBrowser.Providers.Manager.ProviderManager: OnRefreshProgress "cffeae530ea96d3917384f0d9e88033f" 11
[2022-09-26 18:06:59.770 +03:00] [DBG] [68] MediaBrowser.Providers.Manager.ProviderManager: OnRefreshProgress "cffeae530ea96d3917384f0d9e88033f" 12
[2022-09-26 18:06:59.770 +03:00] [DBG] [68] MediaBrowser.Providers.Manager.ProviderManager: OnRefreshProgress "3b7cc628881540e02c869d16aed0acd0" 5
[2022-09-26 18:06:59.770 +03:00] [DBG] [100] MediaBrowser.Providers.Manager.ProviderManager: OnRefreshProgress "5b8c78c20b62e3dd497dae35fedfc581" 5
[2022-09-26 18:06:59.771 +03:00] [DBG] [100] MediaBrowser.Providers.Manager.ProviderManager: OnRefreshProgress "cffeae530ea96d3917384f0d9e88033f" 13
[2022-09-26 18:06:59.771 +03:00] [DBG] [100] MediaBrowser.Providers.Manager.ProviderManager: OnRefreshProgress "5b8c78c20b62e3dd497dae35fedfc581" 10
[2022-09-26 18:06:59.771 +03:00] [DBG] [16] MediaBrowser.Providers.Manager.ProviderManager: OnRefreshComplete "5b8c78c20b62e3dd497dae35fedfc581"
[2022-09-26 18:06:59.771 +03:00] [DBG] [16] MediaBrowser.Providers.Manager.ProviderManager: OnRefreshProgress "cffeae530ea96d3917384f0d9e88033f" 31
[2022-09-26 18:06:59.808 +03:00] [DBG] [68] MediaBrowser.Providers.Manager.ProviderManager: OnRefreshProgress "cffeae530ea96d3917384f0d9e88033f" 32
[2022-09-26 18:06:59.809 +03:00] [DBG] [68] MediaBrowser.Providers.Manager.ProviderManager: OnRefreshProgress "3b7cc628881540e02c869d16aed0acd0" 10
[2022-09-26 18:06:59.809 +03:00] [DBG] [68] MediaBrowser.Providers.Manager.ProviderManager: OnRefreshStart "4f847d6cc9d99264261e6e08d2d6c024"
[2022-09-26 18:06:59.809 +03:00] [DBG] [37] MediaBrowser.Providers.Manager.ProviderManager: OnRefreshStart "a4bf5b7a76e9de09172cd455f33e1c77"
[2022-09-26 18:06:59.809 +03:00] [DBG] [100] MediaBrowser.Providers.Manager.ProviderManager: OnRefreshStart "b65ce8da27b1edbf2b45619d592835ea"
[2022-09-26 18:06:59.809 +03:00] [DBG] [37] MediaBrowser.Providers.Manager.ProviderManager: OnRefreshProgress "3b7cc628881540e02c869d16aed0acd0" 11.333333333333334
[2022-09-26 18:06:59.809 +03:00] [DBG] [100] MediaBrowser.Providers.Manager.ProviderManager: OnRefreshProgress "cffeae530ea96d3917384f0d9e88033f" 32.2
[2022-09-26 18:06:59.809 +03:00] [DBG] [100] MediaBrowser.Providers.Manager.ProviderManager: OnRefreshProgress "3b7cc628881540e02c869d16aed0acd0" 10.666666666666666
[2022-09-26 18:06:59.809 +03:00] [DBG] [37] MediaBrowser.Providers.Manager.ProviderManager: OnRefreshProgress "a4bf5b7a76e9de09172cd455f33e1c77" 5
[2022-09-26 18:06:59.809 +03:00] [DBG] [100] MediaBrowser.Providers.Manager.ProviderManager: OnRefreshProgress "b65ce8da27b1edbf2b45619d592835ea" 5
[2022-09-26 18:06:59.811 +03:00] [DBG] [68] MediaBrowser.Providers.Manager.ProviderManager: OnRefreshProgress "cffeae530ea96d3917384f0d9e88033f" 32.400000000000006
[2022-09-26 18:06:59.811 +03:00] [DBG] [68] MediaBrowser.Providers.Manager.ProviderManager: OnRefreshProgress "3b7cc628881540e02c869d16aed0acd0" 12
[2022-09-26 18:06:59.811 +03:00] [DBG] [68] MediaBrowser.Providers.Manager.ProviderManager: OnRefreshProgress "4f847d6cc9d99264261e6e08d2d6c024" 5
[2022-09-26 18:06:59.812 +03:00] [DBG] [68] MediaBrowser.Providers.Manager.ProviderManager: OnRefreshProgress "cffeae530ea96d3917384f0d9e88033f" 32.599999999999994
[2022-09-26 18:06:59.812 +03:00] [DBG] [68] MediaBrowser.Providers.Manager.ProviderManager: OnRefreshProgress "3b7cc628881540e02c869d16aed0acd0" 12.666666666666666
[2022-09-26 18:06:59.812 +03:00] [DBG] [68] MediaBrowser.Providers.Manager.ProviderManager: OnRefreshProgress "4f847d6cc9d99264261e6e08d2d6c024" 10
[2022-09-26 18:06:59.812 +03:00] [DBG] [100] MediaBrowser.Providers.Manager.ProviderManager: OnRefreshProgress "3b7cc628881540e02c869d16aed0acd0" 13.333333333333334
[2022-09-26 18:06:59.812 +03:00] [DBG] [68] MediaBrowser.Providers.Manager.ProviderManager: OnRefreshComplete "4f847d6cc9d99264261e6e08d2d6c024"
[2022-09-26 18:06:59.812 +03:00] [DBG] [100] MediaBrowser.Providers.Manager.ProviderManager: OnRefreshProgress "b65ce8da27b1edbf2b45619d592835ea" 10
[2022-09-26 18:06:59.812 +03:00] [DBG] [68] MediaBrowser.Providers.Manager.ProviderManager: OnRefreshProgress "cffeae530ea96d3917384f0d9e88033f" 35
[2022-09-26 18:06:59.812 +03:00] [DBG] [68] MediaBrowser.Providers.Manager.ProviderManager: OnRefreshProgress "3b7cc628881540e02c869d16aed0acd0" 25.333333333333336
[2022-09-26 18:06:59.812 +03:00] [DBG] [100] MediaBrowser.Providers.Manager.ProviderManager: OnRefreshComplete "b65ce8da27b1edbf2b45619d592835ea"
[2022-09-26 18:06:59.812 +03:00] [DBG] [100] MediaBrowser.Providers.Manager.ProviderManager: OnRefreshProgress "cffeae530ea96d3917384f0d9e88033f" 37.400000000000006
[2022-09-26 18:06:59.812 +03:00] [DBG] [100] MediaBrowser.Providers.Manager.ProviderManager: OnRefreshProgress "3b7cc628881540e02c869d16aed0acd0" 37.33333333333333
[2022-09-26 18:06:59.812 +03:00] [DBG] [37] MediaBrowser.Providers.Manager.ProviderManager: OnRefreshProgress "cffeae530ea96d3917384f0d9e88033f" 37.599999999999994
[2022-09-26 18:06:59.812 +03:00] [DBG] [37] MediaBrowser.Providers.Manager.ProviderManager: OnRefreshProgress "3b7cc628881540e02c869d16aed0acd0" 38
[2022-09-26 18:06:59.812 +03:00] [DBG] [37] MediaBrowser.Providers.Manager.ProviderManager: OnRefreshProgress "a4bf5b7a76e9de09172cd455f33e1c77" 10
[2022-09-26 18:06:59.812 +03:00] [DBG] [68] MediaBrowser.Providers.Manager.ProviderManager: OnRefreshComplete "a4bf5b7a76e9de09172cd455f33e1c77"
[2022-09-26 18:06:59.812 +03:00] [DBG] [68] MediaBrowser.Providers.Manager.ProviderManager: OnRefreshProgress "cffeae530ea96d3917384f0d9e88033f" 40
[2022-09-26 18:06:59.812 +03:00] [DBG] [68] MediaBrowser.Providers.Manager.ProviderManager: OnRefreshProgress "3b7cc628881540e02c869d16aed0acd0" 50
[2022-09-26 18:06:59.812 +03:00] [DBG] [68] MediaBrowser.Providers.Manager.ProviderManager: OnRefreshComplete "3b7cc628881540e02c869d16aed0acd0"
[2022-09-26 18:06:59.812 +03:00] [DBG] [68] MediaBrowser.Providers.Manager.ProviderManager: OnRefreshProgress "cffeae530ea96d3917384f0d9e88033f" 50
[2022-09-26 18:06:59.812 +03:00] [DBG] [68] MediaBrowser.Providers.Manager.ProviderManager: OnRefreshProgress "cffeae530ea96d3917384f0d9e88033f" 50
[2022-09-26 18:06:59.813 +03:00] [DBG] [76] MediaBrowser.Providers.Folders.FolderMetadataService: Running "FolderImageProvider" for "/Volumes/HDD/Jellyfin media/1 Аудиокниги/tmp"
[2022-09-26 18:06:59.813 +03:00] [DBG] [99] MediaBrowser.Providers.Folders.FolderMetadataService: Running "FolderImageProvider" for "/Volumes/HDD/Jellyfin media/1 Аудиокниги/Аудиокниги [PLlbJKZ0A9TbF3ppbLumJTQrhI6Z9AfU3g]"
[2022-09-26 18:06:59.813 +03:00] [DBG] [66] Jellyfin.Plugin.YoutubeMetadata.Providers.YoutubeLocalImageProvider: YTLocalImage GetImages: "ДЖОРДЖ ОРУЭЛЛ «1984». Аудиокнига. Читает Сергей Чонишвили"
[2022-09-26 18:06:59.813 +03:00] [DBG] [66] Jellyfin.Plugin.YoutubeMetadata.Providers.YoutubeLocalImageProvider: YTLocalImage GetSeriesInfo: "/Volumes/HDD/Jellyfin media/1 Аудиокниги/ДЖОРДЖ ОРУЭЛЛ «1984». Аудиокнига. Читает Сергей Чонишвили [M_NK5q65pwQ]"
[2022-09-26 18:06:59.814 +03:00] [DBG] [68] Jellyfin.Plugin.YoutubeMetadata.Providers.YoutubeLocalImageProvider: YTLocalImage GetImages: "FORD Fiesta V, Mazda II - FRONT - Передние амортизаторы KYB установка"
[2022-09-26 18:06:59.814 +03:00] [DBG] [68] Jellyfin.Plugin.YoutubeMetadata.Providers.YoutubeLocalImageProvider: YTLocalImage GetSeriesInfo: "/Volumes/HDD/Jellyfin media/1 Аудиокниги/FORD Fiesta V, Mazda II - FRONT - Передние амортизаторы KYB установка [Zhp5I1JMWLg]"
[2022-09-26 18:06:59.814 +03:00] [DBG] [66] Jellyfin.Plugin.YoutubeMetadata.Providers.YoutubeLocalImageProvider: YTLocalImage GetSeriesInfo Result: "/Volumes/HDD/Jellyfin media/1 Аудиокниги/ДЖОРДЖ ОРУЭЛЛ «1984». Аудиокнига. Читает Сергей Чонишвили [M_NK5q65pwQ]/poster.jpg"
[2022-09-26 18:06:59.814 +03:00] [DBG] [68] Jellyfin.Plugin.YoutubeMetadata.Providers.YoutubeLocalImageProvider: YTLocalImage GetSeriesInfo Result: "/Volumes/HDD/Jellyfin media/1 Аудиокниги/FORD Fiesta V, Mazda II - FRONT - Передние амортизаторы KYB установка [Zhp5I1JMWLg]/poster.jpg"
[2022-09-26 18:06:59.814 +03:00] [DBG] [68] MediaBrowser.Providers.Movies.MovieMetadataService: Running "FFProbeProvider" for "/Volumes/HDD/Jellyfin media/1 Аудиокниги/FORD Fiesta V, Mazda II - FRONT - Передние амортизаторы KYB установка [Zhp5I1JMWLg]/FORD Fiesta V, Mazda II - FRONT - Передние амортизаторы KYB установка [Zhp5I1JMWLg].mp4"
[2022-09-26 18:06:59.814 +03:00] [DBG] [66] MediaBrowser.Providers.Movies.MovieMetadataService: Running "FFProbeProvider" for "/Volumes/HDD/Jellyfin media/1 Аудиокниги/ДЖОРДЖ ОРУЭЛЛ «1984». Аудиокнига. Читает Сергей Чонишвили [M_NK5q65pwQ]/ДЖОРДЖ ОРУЭЛЛ «1984». Аудиокнига. Читает Сергей Чонишвили [M_NK5q65pwQ].mp4"
[2022-09-26 18:06:59.814 +03:00] [DBG] [68] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: "ffprobe" "-analyzeduration 200M -i file:\"/Volumes/HDD/Jellyfin media/1 Аудиокниги/FORD Fiesta V, Mazda II - FRONT - Передние амортизаторы KYB установка [Zhp5I1JMWLg]/FORD Fiesta V, Mazda II - FRONT - Передние амортизаторы KYB установка [Zhp5I1JMWLg].mp4\" -threads 0 -v warning -print_format json -show_streams -show_chapters -show_format"
[2022-09-26 18:06:59.814 +03:00] [DBG] [66] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: "ffprobe" "-analyzeduration 200M -i file:\"/Volumes/HDD/Jellyfin media/1 Аудиокниги/ДЖОРДЖ ОРУЭЛЛ «1984». Аудиокнига. Читает Сергей Чонишвили [M_NK5q65pwQ]/ДЖОРДЖ ОРУЭЛЛ «1984». Аудиокнига. Читает Сергей Чонишвили [M_NK5q65pwQ].mp4\" -threads 0 -v warning -print_format json -show_streams -show_chapters -show_format"
[2022-09-26 18:06:59.814 +03:00] [DBG] [68] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: Starting ffprobe with args "-analyzeduration 200M -i file:\"/Volumes/HDD/Jellyfin media/1 Аудиокниги/FORD Fiesta V, Mazda II - FRONT - Передние амортизаторы KYB установка [Zhp5I1JMWLg]/FORD Fiesta V, Mazda II - FRONT - Передние амортизаторы KYB установка [Zhp5I1JMWLg].mp4\" -threads 0 -v warning -print_format json -show_streams -show_chapters -show_format"
[2022-09-26 18:06:59.814 +03:00] [DBG] [66] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: Starting ffprobe with args "-analyzeduration 200M -i file:\"/Volumes/HDD/Jellyfin media/1 Аудиокниги/ДЖОРДЖ ОРУЭЛЛ «1984». Аудиокнига. Читает Сергей Чонишвили [M_NK5q65pwQ]/ДЖОРДЖ ОРУЭЛЛ «1984». Аудиокнига. Читает Сергей Чонишвили [M_NK5q65pwQ].mp4\" -threads 0 -v warning -print_format json -show_streams -show_chapters -show_format"
[2022-09-26 18:06:59.842 +03:00] [DBG] [68] MediaBrowser.Providers.Folders.FolderMetadataService: Running "FolderImageProvider" for "/Volumes/HDD/Jellyfin media/1 Аудиокниги/tmp/ДЖОРДЖ ОРУЭЛЛ «1984». Аудиокнига. Читает Сергей Чонишвили [M_NK5q65pwQ]"
[2022-09-26 18:06:59.901 +03:00] [DBG] [68] Emby.Server.Implementations.Data.SqliteItemRepository: "GetItemList" query time (slow): 58.797ms. Query: "select type,data,StartDate,EndDate,ChannelId,IsMovie,IsSeries,EpisodeTitle,IsRepeat,CommunityRating,CustomRating,IndexNumber,IsLocked,PreferredMetadataLanguage,PreferredMetadataCountryCode,Width,Height,DateLastRefreshed,Name,Path,PremiereDate,Overview,ParentIndexNumber,ProductionYear,OfficialRating,ForcedSortName,RunTimeTicks,Size,DateCreated,DateModified,guid,Genres,ParentId,Audio,ExternalServiceId,IsInMixedFolder,DateLastSaved,LockedFields,Studios,Tags,TrailerTypes,OriginalTitle,PrimaryVersionId,DateLastMediaAdded,Album,CriticRating,IsVirtualItem,SeriesName,SeasonName,SeasonId,SeriesId,PresentationUniqueKey,InheritedParentalRatingValue,ExternalSeriesId,Tagline,ProviderIds,Images,ProductionLocations,ExtraIds,TotalBitrate,ExtraType,Artists,AlbumArtists,ExternalId,SeriesPresentationUniqueKey,ShowId,OwnerId from TypedBaseItems A where ParentId=@ParentId AND Images like '%Primary%' ORDER BY IsFolder ASC,SortName ASC LIMIT 1"
[2022-09-26 18:06:59.901 +03:00] [DBG] [66] MediaBrowser.Providers.Folders.FolderMetadataService: Running "FolderImageProvider" for "/Volumes/HDD/Jellyfin media/1 Аудиокниги/tmp/anogus [AnksyaYWrlY]"
[2022-09-26 18:06:59.902 +03:00] [DBG] [99] MediaBrowser.Providers.Manager.ProviderManager: OnRefreshProgress "cffeae530ea96d3917384f0d9e88033f" 62.5
[2022-09-26 18:06:59.908 +03:00] [DBG] [94] MediaBrowser.Providers.Folders.FolderMetadataService: Running "FolderImageProvider" for "/Volumes/HDD/Jellyfin media/1 Аудиокниги/tmp/FORD Fiesta V, Mazda II - FRONT - Передние амортизаторы KYB установка [Zhp5I1JMWLg]"
[2022-09-26 18:06:59.913 +03:00] [DBG] [68] MediaBrowser.Providers.Manager.ProviderManager: OnRefreshProgress "cffeae530ea96d3917384f0d9e88033f" 66.625
[2022-09-26 18:06:59.914 +03:00] [DBG] [66] MediaBrowser.Providers.Manager.ProviderManager: OnRefreshProgress "cffeae530ea96d3917384f0d9e88033f" 70.875
[2022-09-26 18:06:59.919 +03:00] [DBG] [94] MediaBrowser.Providers.Manager.ProviderManager: OnRefreshProgress "cffeae530ea96d3917384f0d9e88033f" 75
[2022-09-26 18:06:59.919 +03:00] [DBG] [94] MediaBrowser.Providers.Manager.ProviderManager: OnRefreshProgress "cffeae530ea96d3917384f0d9e88033f" 75
[2022-09-26 18:07:00.108 +03:00] [DBG] [66] MediaBrowser.Providers.Movies.MovieMetadataService: Running "YoutubeLocalMovieProvider" for "/Volumes/HDD/Jellyfin media/1 Аудиокниги/FORD Fiesta V, Mazda II - FRONT - Передние амортизаторы KYB установка [Zhp5I1JMWLg]/FORD Fiesta V, Mazda II - FRONT - Передние амортизаторы KYB установка [Zhp5I1JMWLg].mp4"
[2022-09-26 18:07:00.108 +03:00] [DBG] [66] Jellyfin.Plugin.YoutubeMetadata.Providers.YoutubeLocalMovieProvider: YTLocal GetMetadata: "/Volumes/HDD/Jellyfin media/1 Аудиокниги/FORD Fiesta V, Mazda II - FRONT - Передние амортизаторы KYB установка [Zhp5I1JMWLg]/FORD Fiesta V, Mazda II - FRONT - Передние амортизаторы KYB установка [Zhp5I1JMWLg].mp4"
[2022-09-26 18:07:00.108 +03:00] [DBG] [66] MediaBrowser.Providers.Movies.MovieMetadataService: "YoutubeLocalMovieProvider" returned no metadata for "/Volumes/HDD/Jellyfin media/1 Аудиокниги/FORD Fiesta V, Mazda II - FRONT - Передние амортизаторы KYB установка [Zhp5I1JMWLg]/FORD Fiesta V, Mazda II - FRONT - Передние амортизаторы KYB установка [Zhp5I1JMWLg].mp4"
[2022-09-26 18:07:00.108 +03:00] [DBG] [66] MediaBrowser.Providers.Movies.MovieMetadataService: Running "MovieNfoProvider" for "/Volumes/HDD/Jellyfin media/1 Аудиокниги/FORD Fiesta V, Mazda II - FRONT - Передние амортизаторы KYB установка [Zhp5I1JMWLg]/FORD Fiesta V, Mazda II - FRONT - Передние амортизаторы KYB установка [Zhp5I1JMWLg].mp4"
[2022-09-26 18:07:00.108 +03:00] [DBG] [66] MediaBrowser.Providers.Movies.MovieMetadataService: "MovieNfoProvider" returned no metadata for "/Volumes/HDD/Jellyfin media/1 Аудиокниги/FORD Fiesta V, Mazda II - FRONT - Передние амортизаторы KYB установка [Zhp5I1JMWLg]/FORD Fiesta V, Mazda II - FRONT - Передние амортизаторы KYB установка [Zhp5I1JMWLg].mp4"
[2022-09-26 18:07:00.288 +03:00] [DBG] [66] MediaBrowser.Providers.Manager.ProviderManager: OnRefreshProgress "cffeae530ea96d3917384f0d9e88033f" 87.5
[2022-09-26 18:07:00.455 +03:00] [DBG] [73] MediaBrowser.Providers.Movies.MovieMetadataService: Running "YoutubeLocalMovieProvider" for "/Volumes/HDD/Jellyfin media/1 Аудиокниги/ДЖОРДЖ ОРУЭЛЛ «1984». Аудиокнига. Читает Сергей Чонишвили [M_NK5q65pwQ]/ДЖОРДЖ ОРУЭЛЛ «1984». Аудиокнига. Читает Сергей Чонишвили [M_NK5q65pwQ].mp4"
[2022-09-26 18:07:00.455 +03:00] [DBG] [73] Jellyfin.Plugin.YoutubeMetadata.Providers.YoutubeLocalMovieProvider: YTLocal GetMetadata: "/Volumes/HDD/Jellyfin media/1 Аудиокниги/ДЖОРДЖ ОРУЭЛЛ «1984». Аудиокнига. Читает Сергей Чонишвили [M_NK5q65pwQ]/ДЖОРДЖ ОРУЭЛЛ «1984». Аудиокнига. Читает Сергей Чонишвили [M_NK5q65pwQ].mp4"
[2022-09-26 18:07:00.455 +03:00] [DBG] [73] MediaBrowser.Providers.Movies.MovieMetadataService: "YoutubeLocalMovieProvider" returned no metadata for "/Volumes/HDD/Jellyfin media/1 Аудиокниги/ДЖОРДЖ ОРУЭЛЛ «1984». Аудиокнига. Читает Сергей Чонишвили [M_NK5q65pwQ]/ДЖОРДЖ ОРУЭЛЛ «1984». Аудиокнига. Читает Сергей Чонишвили [M_NK5q65pwQ].mp4"
[2022-09-26 18:07:00.455 +03:00] [DBG] [73] MediaBrowser.Providers.Movies.MovieMetadataService: Running "MovieNfoProvider" for "/Volumes/HDD/Jellyfin media/1 Аудиокниги/ДЖОРДЖ ОРУЭЛЛ «1984». Аудиокнига. Читает Сергей Чонишвили [M_NK5q65pwQ]/ДЖОРДЖ ОРУЭЛЛ «1984». Аудиокнига. Читает Сергей Чонишвили [M_NK5q65pwQ].mp4"
[2022-09-26 18:07:00.455 +03:00] [DBG] [73] MediaBrowser.Providers.Movies.MovieMetadataService: "MovieNfoProvider" returned no metadata for "/Volumes/HDD/Jellyfin media/1 Аудиокниги/ДЖОРДЖ ОРУЭЛЛ «1984». Аудиокнига. Читает Сергей Чонишвили [M_NK5q65pwQ]/ДЖОРДЖ ОРУЭЛЛ «1984». Аудиокнига. Читает Сергей Чонишвили [M_NK5q65pwQ].mp4"
[2022-09-26 18:07:00.461 +03:00] [DBG] [73] MediaBrowser.Providers.Manager.ProviderManager: OnRefreshProgress "cffeae530ea96d3917384f0d9e88033f" 100
[2022-09-26 18:07:00.461 +03:00] [DBG] [94] MediaBrowser.Providers.Manager.ProviderManager: OnRefreshComplete "cffeae530ea96d3917384f0d9e88033f"
[2022-09-26 18:07:09.374 +03:00] [DBG] [99] Emby.Server.Implementations.Session.WebSocketController: Removing websocket from session "9ebc1469bd162232447fc8834ea31c86"
[2022-09-26 18:07:09.380 +03:00] [DBG] [99] Emby.Server.Implementations.Session.SessionManager: Disposing session controller synchronously "WebSocketController"
[2022-09-26 18:07:09.382 +03:00] [DBG] [99] Emby.Server.Implementations.Session.SessionWebSocketListener: WebSocket "Emby.Server.Implementations.HttpServer.WebSocketConnection" is closed.
[2022-09-26 18:07:09.382 +03:00] [INF] [99] Emby.Server.Implementations.HttpServer.WebSocketManager: WS "192.168.1.70" closed
[2022-09-26 18:07:09.704 +03:00] [DBG] [73] Jellyfin.Api.Auth.CustomAuthenticationHandler: AuthenticationScheme: "CustomAuthentication" was not authenticated.
[2022-09-26 18:07:09.704 +03:00] [DBG] [73] Jellyfin.Networking.Manager.NetworkManager: GetBindInterface: Source: True, External: False:
[2022-09-26 18:07:09.704 +03:00] [DBG] [73] Jellyfin.Networking.Manager.NetworkManager: "192.168.1.70/32": GetBindInterface: Has found matching interface. "192.168.1.70"
[2022-09-26 18:07:09.867 +03:00] [DBG] [94] Jellyfin.Api.Auth.CustomAuthenticationHandler: AuthenticationScheme: "CustomAuthentication" was not authenticated.
[2022-09-26 18:07:10.514 +03:00] [DBG] [100] Emby.Server.Implementations.Session.SessionWebSocketListener: Watching 0 WebSockets.`

**Comment by ankenyr** [comment] 2022-09-26 19:54
I am guessing the library type is audio book? If so that is the problem. I do not support audio books as a media type. You could move this over to a supported library type.

**Comment by pixselious** [comment] 2022-09-26 21:10
No, the library type is movies. This setup has been working for me before I updated.

**Comment by ankenyr** [comment] 2022-09-26 21:44
Then I am unsure what is going on because there are no errors. I also do not see logs I would expect to see if the plugin was working. Possibly something in the configurations is messing with things, at once poing I did allow for skipping of local meta data. You would want to check the configurations directory within the plugin directory for that.

**Comment by pixselious** [comment] 2022-09-26 21:48
Here is the config file:
`<?xml version="1.0" encoding="utf-8"?>
<PluginConfiguration xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
  <ApiKey>string</ApiKey>
  <DisableLocalMetadata>false</DisableLocalMetadata>
</PluginConfiguration>`

Thanks for your help, I'll try to figure this out.

**Comment by pixselious** [comment] 2022-09-26 21:52
This line in the logs caught my attention:
`[2022-09-26 18:07:00.108 +03:00] [DBG] [66] MediaBrowser.Providers.Movies.MovieMetadataService: "YoutubeLocalMovieProvider" returned no metadata for "/Volumes/HDD/Jellyfin media/1 Аудиокниги/FORD Fiesta V, Mazda II - FRONT - Передние амортизаторы KYB установка [Zhp5I1JMWLg]/FORD Fiesta V, Mazda II - FRONT - Передние амортизаторы KYB установка `

**Comment by ankenyr** [comment] 2022-09-26 22:07
Thanks for that, all I can say is the plugin is not returning metadata. What it does is it [exchanges the extension for info.json](https://github.com/ankenyr/jellyfin-youtube-metadata-plugin/blob/master/Jellyfin.Plugin.YoutubeMetadata/Providers/LocalMetadata/AbstractYoutubeLocalProvider.cs#L67) and then checks if it exists, if it does it will start the process of [parsing](https://github.com/ankenyr/jellyfin-youtube-metadata-plugin/blob/master/Jellyfin.Plugin.YoutubeMetadata/Providers/LocalMetadata/AbstractYoutubeLocalProvider.cs#L72-L74) it and returning the correct media type.

If the info.json file is present and has the same file name as the mp4 it should find it.

If you know enough about C# to compile the plugin you could add a few logging lines in there to help troubleshoot. Specifically following line 67 log out the file name it checks for existence and see if it matches or for some reason doesn't.

**Comment by pixselious** [comment] 2022-09-26 22:14
I will try to help.

For now, I reverted to 1.0.3.4 and everything works as intended. It shows up as "superseded" but works.

If someone is having the same issue:
- I deleted the current plugin (from the file system, not the web UI)
- Installed the older version
- Restarted the server
- It automatically fetched the latest version, but I deleted it.

**Comment by ankenyr** [comment] 2022-09-26 23:05
Did you only downgrade the plugin or did you downgrade the server?

**Comment by pixselious** [comment] 2022-09-27 05:16
I downgraded the plugin to the oldest version that works on Jf 1.8.x

**Comment by prahal** [comment] 2022-11-10 14:00
This likely will be fixed by https://github.com/ankenyr/jellyfin-youtube-metadata-plugin/pull/66.
Fribb feedback is of interest but the fix is good as is (and the plugin has a regression without it). Maybe an issue should be opened with Fribb improvement request.
At least without this pull request fix and local install I get no metadata from info.json. With it all is fine (and I believe reverting to pre 1.0.3.9 will make the issue that the plugin only coped with one episode per containing folder rapper, ie fixed by commit https://github.com/ankenyr/jellyfin-youtube-metadata-plugin/commit/93f4b2784bca74133f7b9ad08c358ba4f608cff0).

**Comment by truppelito** [comment] 2022-11-19 11:58
+1 for this problem. I'm having what seems to be the same issue on YoutubeMetadata 1.0.3.8 and Jellyfin 10.8.7. For example, inside my Youtube library folder (library type = Movies) I have a folder with the name "The Greatest Motor Race EVER - Josh Revell - 20221014". Inside that folder I have the files "The Greatest Motor Race EVER - Josh Revell - 20221014 [XMkzDMAP-80].mkv", "The Greatest Motor Race EVER - Josh Revell - 20221014 [XMkzDMAP-80].info.json", "The Greatest Motor Race EVER - Josh Revell - 20221014 [XMkzDMAP-80].description", "The Greatest Motor Race EVER - Josh Revell - 20221014 [XMkzDMAP-80].webp". Yet, no metadata is shown in the Jellyfin interface.

**Comment by t2691** [comment] 2022-12-02 02:21
Jellyfin Version: 10.8.7
Running in docker

Verified same issue using the latest plugin and youtube videos downloaded with yt-dlp . 
Downgrading the plugin to 1.0.3.4 seems to have resolved the issue.

I saw the issue when trying to create a directory structure inside the youtube library.

Youtube
   Channel 1
   Channel 2
Videos in the top level would show their metadata and pictures below that would not.

The issue also persisted if I added another library and pointed to the sub directories directly.
Youtube\Channel 1

After reverting to plugin version 1.0.3.4 and going back to the youtube library with subdirectories, metadata and images are working again.

**Comment by b-col** [comment] 2023-02-22 13:39
I am experiencing the same issue with a structured library. Downgrading the plugin to 1.0.3.4 resolves the problem.

**Comment by ankenyr** [comment] 2024-05-26 00:45
This has been resolved in the latest version I believe.

**Closed by ankenyr** 2024-05-26 00:45 UTC

**Comment by pixselious** [comment] 2024-06-08 15:24
Can confirm! I installed Jellyfin 10.9.6 and Plugin 1.0.3.12, fed them the same data and everything works as expected! Thank you ❤️.
